- name: Run using a project directory
  hosts: all
  gather_facts: no
  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true
    - name: Install Python Docker
      pip:
        name: docker
    - name: Install Python Docker
      pip:
        name: docker-compose
    - name: Create project directory
      file:
        path: /opt/pastegraph
        state: directory
    - name: Copy docker-compose.yml
      copy:
        src: docker-compose.yml
        dest: /opt/pastegraph/docker-compose.yml
        owner: root
        group: root
        mode: '0644'
    - name: Run pastegraph
      community.docker.docker_compose:
        project_src: /opt/pastegraph